version: "3.5"
services:
  mock-server:
    container_name: mock-server
    build: 
      context: .
      dockerfile: test/MockServer/Dockerfile
    extra_hosts:
       - "host.docker.internal:host-gateway"
    ports:
      - "3000:80" 
    hostname: "mock-server"
    networks:
      - pokenetwork
  
   
networks:
  pokenetwork:
    name: pokenetwork