version: "3.5"
services:
  mock-server:
    image: clue/json-server:latest
    ports:
      - "3000:80" 
    hostname: "mock-server"
    networks:
      - pokenetwork
    volumes:
      - ./docker/json-server/data.json/:/data/db.json


networks:
  pokenetwork:
    name: pokenetwork